[project]
name = "zephyrscale-mcp"
version = "0.1.0"
description = "An MCP server for zephyr scale"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "httpx>=0.28.1",
    "mcp[cli]>=1.9.4",
]